#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=x10

mkdir -p ../../../vendor/se/$DEVICE/proprietary
unzip -j -o ../../../${DEVICE}_update.zip system/bin/akmd2 system/bin/mm-venc-omx-test system/etc/01_qcomm_omx.cfg system/etc/firmware/yamato_pfp.fw system/etc/firmware/yamato_pm4.fw system/lib/egl/libEGL_adreno200.so system/lib/egl/libGLESv1_CM_adreno200.so system/lib/egl/libGLESv2_adreno200.so system/lib/egl/libq3dtools_adreno200.so system/lib/libcamera.so system/lib/libgps.so system/lib/libgsl.so system/lib/libril_qc_1.so system/lib/liboemcamera.so system/lib/libOmxVdec.so -d ../../../vendor/se/$DEVICE/proprietary
chmod 755 ../../../vendor/se/$DEVICE/proprietary/bin/akmd2
chmod 755 ../../../vendor/se/$DEVICE/proprietary/bin/mm-venc-omx-test

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/se/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/__DEVICE__/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \\
    vendor/se/__DEVICE__/proprietary/lib/libgps.so:obj/lib/libgps.so \\
    vendor/se/__DEVICE__/proprietary/lib/libcamera.so:obj/lib/libcamera.so

# All the blobs necessary for x10
PRODUCT_COPY_FILES += \\
    vendor/se/__DEVICE__/proprietary/bin/akmd2:/system/bin/akmd2 \\
    vendor/se/__DEVICE__/proprietary/bin/mm-venc-omx-test:/system/bin/mm-venc-omx-test \\
    vendor/se/__DEVICE__/proprietary/etc/01_qcomm_omx.cfg:/system/etc/01_qcomm_omx.cfg \\
    vendor/se/__DEVICE__/proprietary/etc/firmware/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \\
    vendor/se/__DEVICE__/proprietary/etc/firmware/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw \\
    vendor/se/__DEVICE__/proprietary/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \\
    vendor/se/__DEVICE__/proprietary/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \\
    vendor/se/__DEVICE__/proprietary/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \\
    vendor/se/__DEVICE__/proprietary/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \\
    vendor/se/__DEVICE__/proprietary/lib/libcamera.so:/system/lib/libcamera.so \\
    vendor/se/__DEVICE__/proprietary/lib/libgps.so:/system/lib/libgps.so \\
    vendor/se/__DEVICE__/proprietary/lib/libgsl.so:/system/lib/libgsl.so \\
    vendor/se/__DEVICE__/proprietary/lib/libhtc_ril.so:/system/lib/libril_qc_1.so \\
    vendor/se/__DEVICE__/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \\
    vendor/se/__DEVICE__/proprietary/lib/libOmxVdec.so:/system/lib/libOmxVdec.so

EOF

./setup-makefiles.sh
